import { notFound } from "next/navigation";
import { sanityWriteClient } from "@/lib/sanityWriteClient";
import { OwnerLeadWorkspace } from "@/components/owner/leads/OwnerLeadWorkspace";
import { getCoverageProfile,getDoorsAccess,getProjectType,getRackLocation,getScopeNotes,getSquareFootage,getTimeline,getWifiLayout,getWiringStyle,type SmartNetEstimateSnapshot } from "@/lib/estimate-snapshot";
type LeadDoc={_id:string;contactName?:string|null;contactEmail?:string|null;contactPhone?:string|null;leadSource?:string|null;projectType?:string|null;requestedServices?:string|null;jobLocationNote?:string|null;estimateRoughRange?:string|null;estimateTotal?:number|null;createdAt?:string|null;dateISO?:string|null;timeSlot?:string|null;ownerFollowUpDueAt?:string|null;crmStage?:string|null;crmPriority?:string|null;crmAssignedTo?:string|null;crmLostReason?:string|null;ownerNotes?:string|null;appointmentType?:string|null;estimateNotes?:string|null;notes?:string|null;squareFootage?:number|null;focus?:string[]|null;coverageProfile?:string|null;wifiLayout?:string|null;doorsAccess?:string|null;extras?:string[]|null;wiringStyle?:string|null;rackLocation?:string|null;timeline?:string|null;rawEstimateJson?:string|null;walkthroughScheduledAt?:string|null;walkthroughStatus?:string|null;walkthroughSiteNotes?:string|null;walkthroughEquipmentNotes?:string|null;walkthroughCableNotes?:string|null;walkthroughPowerNetworkNotes?:string|null;attribution?:{provider?:string|null;campaign?:string|null;adSet?:string|null;ad?:string|null}|null};
type Activity={_id:string;activityType?:string|null;summary?:string|null;createdAt?:string|null};
function parseEstimate(raw?:string|null):SmartNetEstimateSnapshot|null{if(!raw)return null;try{const parsed=JSON.parse(raw)as unknown;return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as SmartNetEstimateSnapshot:null}catch{return null}}
function hydrateLegacyEstimate(lead:LeadDoc):LeadDoc{const estimate=parseEstimate(lead.rawEstimateJson);if(!estimate)return lead;return{...lead,projectType:lead.projectType||getProjectType(estimate),squareFootage:lead.squareFootage??getSquareFootage(estimate),coverageProfile:lead.coverageProfile||getCoverageProfile(estimate),wifiLayout:lead.wifiLayout||getWifiLayout(estimate),doorsAccess:lead.doorsAccess||getDoorsAccess(estimate),wiringStyle:lead.wiringStyle||getWiringStyle(estimate),rackLocation:lead.rackLocation||getRackLocation(estimate),timeline:lead.timeline||getTimeline(estimate),estimateNotes:lead.estimateNotes||getScopeNotes(estimate),focus:lead.focus?.length?lead.focus:estimate.focus??null,extras:lead.extras?.length?lead.extras:estimate.extras??null}}
export default async function LeadWorkspacePage({params}:{params:Promise<{id:string}>}){const{id}=await params;const[lead,activity]=await Promise.all([sanityWriteClient.fetch<LeadDoc|null>(`*[_type=="walkthroughBooking"&&_id==$id][0]{_id,contactName,contactEmail,contactPhone,leadSource,projectType,requestedServices,jobLocationNote,estimateRoughRange,estimateTotal,createdAt,dateISO,timeSlot,ownerFollowUpDueAt,crmStage,crmPriority,crmAssignedTo,crmLostReason,ownerNotes,appointmentType,estimateNotes,notes,squareFootage,focus,coverageProfile,wifiLayout,doorsAccess,extras,wiringStyle,rackLocation,timeline,rawEstimateJson,walkthroughScheduledAt,walkthroughStatus,walkthroughSiteNotes,walkthroughEquipmentNotes,walkthroughCableNotes,walkthroughPowerNetworkNotes,attribution}`,{id}),sanityWriteClient.fetch<Activity[]>(`*[_type=="smartnetLeadActivity"&&leadId==$id]|order(createdAt desc)[0...100]{_id,activityType,summary,createdAt}`,{id})]);if(!lead)notFound();return <OwnerLeadWorkspace lead={hydrateLegacyEstimate(lead)} activity={activity}/>}
