import Link from "next/link";
import { CalendarDays, CheckCircle2, Clock3, MapPin, Network, Phone, Mail, ArrowLeft, ArrowRight, CircleDollarSign, ShieldCheck } from "lucide-react";
import { sanityWriteClient } from "@/lib/sanityWriteClient";

type Walkthrough = {
  _id: string; status?: string|null; appointmentType?: string|null; dateISO?: string|null; timeSlot?: string|null;
  contactName?: string|null; contactEmail?: string|null; contactPhone?: string|null; locationLabel?: string|null; locationType?: string|null;
  estimateRoughRange?: string|null; estimateTotal?: number|null; followupWalkthroughDateISO?: string|null; followupWalkthroughTimeSlot?: string|null;
};

async function getWalkthroughs() {
  return sanityWriteClient.fetch<Walkthrough[]>(`*[_type == "walkthroughBooking"] | order(dateISO asc){_id,status,appointmentType,dateISO,timeSlot,contactName,contactEmail,contactPhone,locationLabel,locationType,estimateRoughRange,estimateTotal,followupWalkthroughDateISO,followupWalkthroughTimeSlot}`);
}
function dateLabel(v?:string|null){if(!v)return"Not scheduled";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric",year:"numeric",timeZone:"America/New_York"})}
function money(v?:number|null){return v==null?null:new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v)}
function completed(w:Walkthrough){return (w.status||"").toLowerCase().includes("complete")||(w.status||"").toLowerCase().includes("done")}
function effectiveDate(w:Walkthrough){return w.followupWalkthroughDateISO||w.dateISO||null}
function effectiveTime(w:Walkthrough){return w.followupWalkthroughTimeSlot||w.timeSlot||null}

export default async function WalkthroughsPage(){
 const rows=await getWalkthroughs(); const now=new Date();
 const upcoming=rows.filter(w=>!completed(w)&&effectiveDate(w)&&new Date(effectiveDate(w)!)>=now);
 const past=rows.filter(w=>completed(w)||(effectiveDate(w)&&new Date(effectiveDate(w)!)<now));
 const today=upcoming.filter(w=>{const d=new Date(effectiveDate(w)!);return d.toDateString()===now.toDateString()});
 const value=upcoming.reduce((s,w)=>s+(w.estimateTotal||0),0);
 return <main className="min-h-screen bg-[#020713] text-slate-100"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_0%,rgba(0,132,255,.14),transparent_30%),radial-gradient(circle_at_85%_10%,rgba(34,211,238,.09),transparent_28%),linear-gradient(rgba(15,34,58,.17)_1px,transparent_1px),linear-gradient(90deg,rgba(15,34,58,.17)_1px,transparent_1px)] bg-[size:auto,auto,40px_40px,40px_40px]"/>
 <header className="sticky top-0 z-30 border-b border-cyan-400/10 bg-[#020713]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-blue-400/30 bg-blue-500/10"><Network className="h-4 w-4 text-cyan-300"/></div><div><p className="text-sm font-semibold">Smart<span className="text-blue-400">NET</span></p><p className="text-[9px] uppercase tracking-[.24em] text-slate-600">Walkthrough Operations</p></div></div><Link href="/owner/dashboard" className="flex items-center gap-2 rounded-xl border border-white/5 bg-white/[.03] px-3 py-2 text-xs text-slate-300"><ArrowLeft className="h-3.5 w-3.5"/>Command Center</Link></div></header>
 <div className="relative mx-auto max-w-[1500px] space-y-5 px-3 pb-24 pt-5 sm:px-6 lg:px-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-cyan-500">Field Operations</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Walkthrough Command</h1><p className="mt-1 text-xs text-slate-500">Every site visit from scheduled assessment to quote handoff.</p></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={<CalendarDays className="h-5 w-5 text-cyan-300"/>} label="Upcoming" value={String(upcoming.length)}/><Metric icon={<Clock3 className="h-5 w-5 text-blue-300"/>} label="Today" value={String(today.length)}/><Metric icon={<CheckCircle2 className="h-5 w-5 text-emerald-300"/>} label="Completed / Past" value={String(past.length)}/><Metric icon={<CircleDollarSign className="h-5 w-5 text-amber-300"/>} label="Scheduled Value" value={money(value)||"$0"}/></div>
 <section className="overflow-hidden rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))]"><div className="border-b border-white/5 p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-300"/><h2 className="text-sm font-semibold">Upcoming Walkthroughs</h2></div><p className="mt-1 text-[10px] text-slate-600">Mobile-ready field queue</p></div><div className="divide-y divide-white/5">{upcoming.length?upcoming.map(w=><WalkthroughRow key={w._id} w={w}/>):<div className="p-10 text-center text-xs text-slate-600">No upcoming walkthroughs.</div>}</div></section>
 <section className="overflow-hidden rounded-2xl border border-white/5 bg-[#050d1b]/80"><div className="p-5"><h2 className="text-sm font-semibold">Completed & Past Visits</h2><p className="mt-1 text-[10px] text-slate-600">History stays attached to the customer record</p></div><div className="divide-y divide-white/5">{past.slice(0,20).map(w=><WalkthroughRow key={w._id} w={w} muted/>)}</div></section>
 </div></main>
}
function WalkthroughRow({w,muted=false}:{w:Walkthrough;muted?:boolean}){const date=effectiveDate(w),time=effectiveTime(w);const estimate=w.estimateRoughRange||money(w.estimateTotal)||"No estimate";return <div className={`p-4 sm:p-5 ${muted?"opacity-65":""}`}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><Link href={`/owner/booking/${w._id}`} className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-white">{w.contactName||"Unknown customer"}</p>{w.followupWalkthroughDateISO&&<span className="rounded-full border border-violet-400/20 bg-violet-500/10 px-2 py-1 text-[8px] uppercase tracking-wider text-violet-300">Follow-up</span>}</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-slate-500"><span className="flex items-center gap-1"><CalendarDays className="h-3 w-3 text-cyan-500"/>{dateLabel(date)}{time?` · ${time}`:""}</span><span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-blue-500"/>{w.locationLabel||w.locationType||"Location not specified"}</span><span className="text-amber-300/80">{estimate}</span></div></Link><div className="grid grid-cols-3 gap-2 lg:flex">{w.contactPhone?<a href={`tel:${w.contactPhone}`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-cyan-400/15 bg-cyan-500/[.05] px-3 text-[10px] text-cyan-200"><Phone className="h-3.5 w-3.5"/><span className="hidden sm:inline">Call</span></a>:<span/>}{w.contactEmail?<a href={`mailto:${w.contactEmail}`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-blue-400/15 bg-blue-500/[.05] px-3 text-[10px] text-blue-200"><Mail className="h-3.5 w-3.5"/><span className="hidden sm:inline">Email</span></a>:<span/>}<Link href={`/owner/booking/${w._id}`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 text-[10px] text-slate-200">Open<ArrowRight className="h-3.5 w-3.5"/></Link></div></div></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))] p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/5 bg-white/[.03]">{icon}</div><div><p className="text-[9px] uppercase tracking-[.16em] text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div></div></div>}
