import { NextRequest, NextResponse } from "next/server";
import { sanityWriteClient } from "@/lib/sanityWriteClient";

type LeadPatch={stage?:string;priority?:string;assignedTo?:string|null;nextFollowUpAt?:string|null;lostReason?:string|null;note?:string|null;contactName?:string|null;contactEmail?:string|null;contactPhone?:string|null;jobLocationNote?:string|null;projectType?:string|null;requestedServices?:string|null};
type Booking={_id:string;contactName?:string|null;contactEmail?:string|null;contactPhone?:string|null;jobLocationNote?:string|null;projectType?:string|null;requestedServices?:string|null;estimateTotal?:number|null;estimateRoughRange?:string|null;crmStage?:string|null};
const allowedStages=new Set(["new","contacted","qualified","walkthrough","quote","negotiating","won","lost"]),allowedPriorities=new Set(["low","normal","high","hot"]);
function parseRange(v?:string|null){if(!v)return 0;const parts=v.split(/[–-]/);const raw=(parts[1]||parts[0]||"").replace(/[^0-9.]/g,"");const n=Number(raw);return Number.isFinite(n)?n:0}
function clean(v:string|null|undefined){return typeof v==="string"?v.trim()||null:v??null}
async function createWonArtifacts(booking:Booking,now:string){const existing=await sanityWriteClient.fetch<{_id:string}|null>(`*[_type=="smartnetJob"&&sourceBookingId==$id][0]{_id}`,{id:booking._id});if(existing)return existing._id;const amount=booking.estimateTotal??parseRange(booking.estimateRoughRange);const job=await sanityWriteClient.create({_type:"smartnetJob",sourceBookingId:booking._id,customerName:booking.contactName||"Unknown customer",customerEmail:booking.contactEmail||null,customerPhone:booking.contactPhone||null,location:booking.jobLocationNote||null,projectType:booking.projectType||null,services:booking.requestedServices||null,status:"new",estimateTotal:amount||null,createdAt:now,updatedAt:now});await sanityWriteClient.create({_type:"smartnetWorkOrder",title:`Installation - ${booking.contactName||"Customer"}`,customerName:booking.contactName||"Unknown customer",jobId:job._id,sourceBookingId:booking._id,status:"open",description:booking.requestedServices||booking.projectType||"SmartNET installation scope",createdAt:now,updatedAt:now});return job._id}
export async function PATCH(req:NextRequest,context:{params:Promise<{id:string}>}){try{const{id}=await context.params;const body=(await req.json())as LeadPatch;const booking=await sanityWriteClient.fetch<Booking|null>(`*[_type=="walkthroughBooking"&&_id==$id][0]{_id,contactName,contactEmail,contactPhone,jobLocationNote,projectType,requestedServices,estimateTotal,estimateRoughRange,crmStage}`,{id});if(!booking)return NextResponse.json({ok:false,error:"Lead not found"},{status:404});const now=new Date().toISOString();const patch:Record<string,unknown>={crmUpdatedAt:now};if(body.stage&&allowedStages.has(body.stage))patch.crmStage=body.stage;if(body.priority&&allowedPriorities.has(body.priority))patch.crmPriority=body.priority;if(body.assignedTo!==undefined)patch.crmAssignedTo=clean(body.assignedTo);if(body.nextFollowUpAt!==undefined)patch.ownerFollowUpDueAt=body.nextFollowUpAt||null;if(body.lostReason!==undefined)patch.crmLostReason=clean(body.lostReason);if(body.contactName!==undefined)patch.contactName=clean(body.contactName);if(body.contactEmail!==undefined)patch.contactEmail=clean(body.contactEmail);if(body.contactPhone!==undefined)patch.contactPhone=clean(body.contactPhone);if(body.jobLocationNote!==undefined)patch.jobLocationNote=clean(body.jobLocationNote);if(body.projectType!==undefined)patch.projectType=clean(body.projectType);if(body.requestedServices!==undefined)patch.requestedServices=clean(body.requestedServices);await sanityWriteClient.patch(id).set(patch).commit();const current={...booking,...patch}as Booking;let createdJobId:string|null=null;if(body.stage==="won"&&booking.crmStage!=="won")createdJobId=await createWonArtifacts(current,now);const changes=Object.keys(patch).filter(k=>k!=="crmUpdatedAt");if(changes.length)await sanityWriteClient.create({_type:"smartnetLeadActivity",leadId:id,customerName:current.contactName||"Unknown customer",activityType:body.stage==="won"?"won":body.stage==="lost"?"lost":"crm_update",summary:body.stage==="won"?`Lead won${createdJobId?` · Job ${createdJobId} created`:""}`:body.stage==="lost"?`Lead lost${body.lostReason?`: ${body.lostReason}`:""}`:`Updated ${changes.join(", ")}`,createdAt:now});if(body.note?.trim())await sanityWriteClient.create({_type:"smartnetLeadActivity",leadId:id,customerName:current.contactName||"Unknown customer",activityType:"note",summary:body.note.trim(),createdAt:now});await sanityWriteClient.create({_type:"smartnetActivity",eventType:body.stage==="won"?"lead_won":body.stage==="lost"?"lead_lost":"lead_updated",customerName:current.contactName||"Unknown customer",sourceId:id,sourceType:"walkthroughBooking",occurredAt:now,metadata:{stage:body.stage||null,createdJobId}});return NextResponse.json({ok:true,createdJobId})}catch(error){console.error("[owner lead patch]",error);return NextResponse.json({ok:false,error:"Failed to update lead"},{status:500})}}
export async function DELETE(_req:NextRequest,context:{params:Promise<{id:string}>}){try{const{id}=await context.params;if(!id)return NextResponse.json({ok:false,error:"Missing lead id"},{status:400});const booking=await sanityWriteClient.fetch<{_id:string}|null>(`*[_type=="walkthroughBooking"&&_id==$id][0]{_id}`,{id});if(!booking?._id)return NextResponse.json({ok:false,error:"Lead not found"},{status:404});await sanityWriteClient.delete(booking._id);return NextResponse.json({ok:true,deletedId:booking._id})}catch(error){console.error("[owner lead delete] error",error);return NextResponse.json({ok:false,error:"Failed to delete lead"},{status:500})}}
