import { NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { sanityWriteClient } from "@/lib/sanityWriteClient";
import { can, hashTeamPassword, readOwnerSession, type OwnerRole } from "@/lib/owner/ownerSession";

async function authorize(){const c=await cookies();const session=readOwnerSession(c.get("smartnet_owner_session")?.value);return session&&can(session.role,"team")?session:null}
export async function GET(){if(!await authorize())return NextResponse.json({ok:false},{status:403});const members=await sanityWriteClient.fetch(`*[_type=="smartnetTeamMember"]|order(createdAt asc){_id,name,email,username,role,active,createdAt,lastLoginAt}`);return NextResponse.json({ok:true,members})}
export async function POST(req:NextRequest){if(!await authorize())return NextResponse.json({ok:false},{status:403});try{const b=await req.json();const name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),username=String(b.username||email).trim().toLowerCase(),password=String(b.password||""),role=(b.role||"sales") as OwnerRole;if(!name||!username||password.length<8)return NextResponse.json({ok:false,error:"Name, username/email and an 8+ character password are required."},{status:400});if(!["owner","admin","sales","marketing","technician"].includes(role))return NextResponse.json({ok:false,error:"Invalid role"},{status:400});const exists=await sanityWriteClient.fetch(`*[_type=="smartnetTeamMember" && (lower(email)==lower($email)||lower(username)==lower($username))][0]._id`,{email,username});if(exists)return NextResponse.json({ok:false,error:"A team member already uses that email/username."},{status:409});const doc=await sanityWriteClient.create({_type:"smartnetTeamMember",name,email:email||null,username,role,active:true,passwordHash:hashTeamPassword(password),createdAt:new Date().toISOString()});return NextResponse.json({ok:true,id:doc._id})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Unable to add team member"},{status:400})}}
export async function PATCH(req:NextRequest){if(!await authorize())return NextResponse.json({ok:false},{status:403});try{const b=await req.json();const id=String(b.id||"");if(!id)return NextResponse.json({ok:false,error:"Missing id"},{status:400});const patch:any={};if(typeof b.active==="boolean")patch.active=b.active;if(b.role&&["owner","admin","sales","marketing","technician"].includes(b.role))patch.role=b.role;if(b.name)patch.name=String(b.name).trim();if(b.password){const p=String(b.password);if(p.length<8)return NextResponse.json({ok:false,error:"Password must be at least 8 characters."},{status:400});patch.passwordHash=hashTeamPassword(p)}await sanityWriteClient.patch(id).set({...patch,updatedAt:new Date().toISOString()}).commit();return NextResponse.json({ok:true})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:"Unable to update team member"},{status:400})}}
