"use client";

import type { FC, FormEvent, ReactNode } from "react";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, BarChart3, Bell, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileText, LayoutDashboard, Menu, Network, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2, TriangleAlert, Users, UserRoundSearch, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { OwnerLogoutButton } from "../../app/owner/access/OwnerLogoutButton";
import type { OwnerDashboardData } from "@/app/owner/dashboard/page";

type Props=OwnerDashboardData;
type DeleteTarget={id:string;name:string}|null;
type LeadForm={customerName:string;email:string;phone:string;projectType:string;services:string;source:string;address:string;notes:string;roughLow:string;roughHigh:string};
const emptyLead:LeadForm={customerName:"",email:"",phone:"",projectType:"",services:"",source:"Phone / Referral",address:"",notes:"",roughLow:"",roughHigh:""};
const navItems=[{label:"Dashboard",icon:LayoutDashboard,href:"/owner/dashboard"},{label:"Calendar",icon:CalendarDays,href:"/owner/dashboard/calendar"},{label:"Leads",icon:UserRoundSearch,href:"#leads"},{label:"Walkthroughs",icon:ShieldCheck,href:"/owner/walkthroughs"},{label:"Jobs",icon:BriefcaseBusiness,href:"/owner/jobs"},{label:"Quotes",icon:FileText,href:"/owner/quotes"},{label:"Customers",icon:Users},{label:"Follow-Ups",icon:Clock3},{label:"Reports",icon:BarChart3},{label:"Settings",icon:Settings}];
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const when=(iso:string|null)=>{if(!iso)return"Not scheduled";const d=new Date(iso);return Number.isNaN(d.getTime())?"Not scheduled":d.toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})};
const eventLabel=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export const OwnerDashboardClient:FC<Props>=(props)=>{
 const[menu,setMenu]=useState(false),[query,setQuery]=useState(""),[deleteTarget,setDeleteTarget]=useState<DeleteTarget>(null),[deleting,setDeleting]=useState(false),[bookings,setBookings]=useState(props.bookings),[notice,setNotice]=useState<string|null>(null),[showAdd,setShowAdd]=useState(false),[saving,setSaving]=useState(false),[lead,setLead]=useState<LeadForm>(emptyLead);
 const pipeline=bookings.reduce((s,b)=>s+(b.roughHigh??b.roughLow??0),0),active=bookings.filter(b=>b.status!=="completed").length,completed=bookings.filter(b=>b.status==="completed").length;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return bookings.filter(b=>!q||b.customerName.toLowerCase().includes(q)||b.customerEmail?.toLowerCase().includes(q)||b.customerPhone?.includes(q)).slice(0,8)},[bookings,query]);
 const stages=[{label:"New Leads",value:bookings.filter(b=>b.status==="new").length,color:"#2587ff"},{label:"Walkthrough Scheduled",value:bookings.filter(b=>b.status==="scheduled").length,color:"#21d7df"},{label:"Follow-Up",value:bookings.filter(b=>b.status==="followup").length,color:"#9957ef"},{label:"Completed",value:completed,color:"#4ade80"}];const total=Math.max(1,stages.reduce((s,x)=>s+x.value,0));
 const upcoming=bookings.filter(b=>b.scheduledForISO&&new Date(b.scheduledForISO)>=new Date()).sort((a,b)=>new Date(a.scheduledForISO!).getTime()-new Date(b.scheduledForISO!).getTime()).slice(0,4);const recent=props.leadEvents.slice().sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime()).slice(0,6);
 const points=useMemo(()=>Array.from({length:12},(_,i)=>{const base=Math.max(8,pipeline/12);return Math.round(base*(.55+i*.045)+((i%3)-1)*base*.08)}),[pipeline]);const maxPoint=Math.max(1,...points);const line=points.map((p,i)=>`${(i/(points.length-1))*100},${88-(p/maxPoint)*70}`).join(" ");
 async function removeLead(){if(!deleteTarget)return;setDeleting(true);try{const r=await fetch(`/api/owner/leads/${encodeURIComponent(deleteTarget.id)}`,{method:"DELETE"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Delete failed");const id=deleteTarget.id,name=deleteTarget.name;setBookings(v=>v.filter(b=>b.id!==id));setDeleteTarget(null);toast(`${name} removed.`)}catch(e){toast(e instanceof Error?e.message:"Could not remove lead.")}finally{setDeleting(false)}}
 function toast(v:string){setNotice(v);window.setTimeout(()=>setNotice(null),3200)}
 async function addLead(e:FormEvent){e.preventDefault();setSaving(true);try{const payload={...lead,roughLow:lead.roughLow?Number(lead.roughLow):null,roughHigh:lead.roughHigh?Number(lead.roughHigh):null};const r=await fetch("/api/owner/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add lead");setBookings(v=>[{id:j.id,customerName:lead.customerName.trim(),customerEmail:lead.email.trim()||null,customerPhone:lead.phone.trim()||null,bookingType:"initial",scheduledForISO:null,status:"new",roughLow:payload.roughLow,roughHigh:payload.roughHigh},...v]);setLead(emptyLead);setShowAdd(false);toast("Lead added to SmartNET pipeline.")}catch(e){toast(e instanceof Error?e.message:"Could not add lead.")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#010713] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_0%,rgba(0,119,255,.18),transparent_28%),radial-gradient(circle_at_88%_10%,rgba(0,220,255,.10),transparent_24%),linear-gradient(rgba(12,55,96,.14)_1px,transparent_1px),linear-gradient(90deg,rgba(12,55,96,.14)_1px,transparent_1px)] bg-[size:auto,auto,46px_46px,46px_46px]"/>
 <aside className="fixed inset-y-0 left-0 z-40 hidden w-[230px] border-r border-blue-400/20 bg-[#020b19]/95 px-4 py-5 backdrop-blur-xl lg:flex lg:flex-col"><Brand/><div className="my-5 h-16 bg-[radial-gradient(circle_at_center,rgba(0,174,255,.32),transparent_48%)]"/><OwnerNav/><div className="mt-auto space-y-3"><div className="rounded-2xl border border-cyan-400/20 bg-cyan-500/[.05] p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-cyan-300/30 bg-cyan-500/10 shadow-[0_0_22px_rgba(34,211,238,.2)]"><Sparkles className="h-4 w-4 text-cyan-200"/></div><div><p className="text-xs font-semibold">SmartNET Admin</p><p className="text-[9px] text-cyan-400">Owner</p></div></div></div><OwnerLogoutButton className="w-full justify-start border-0 bg-transparent text-xs text-slate-400" variant="outline" next="/owner/access"/></div></aside>
 {menu&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/80" onClick={()=>setMenu(false)}/><aside className="relative h-full w-[84%] max-w-[300px] border-r border-cyan-400/20 bg-[#020b19] p-5"><div className="flex items-center justify-between"><Brand/><Button variant="ghost" size="icon" onClick={()=>setMenu(false)}><X/></Button></div><div className="mt-8"><OwnerNav onNavigate={()=>setMenu(false)}/></div></aside></div>}
 <section className="relative min-h-screen lg:ml-[230px]"><header className="sticky top-0 z-30 border-b border-blue-400/10 bg-[#010713]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[78px] max-w-[1700px] items-center justify-between gap-3 px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMenu(true)}><Menu className="h-5 w-5"/></Button><div><h1 className="text-lg font-semibold sm:text-2xl">Welcome back, SmartNET Admin 👋</h1><p className="mt-1 text-[10px] text-slate-500 sm:text-xs">Here’s what’s happening with your business today.</p></div></div><div className="flex items-center gap-2"><button onClick={()=>setShowAdd(true)} className="flex h-10 items-center gap-2 rounded-xl border border-blue-300/30 bg-blue-600/20 px-3 text-[10px] font-semibold text-blue-100 shadow-[0_0_24px_rgba(37,99,235,.16)] hover:bg-blue-500/30"><Plus className="h-4 w-4"/>Add Lead</button><span className="hidden rounded-full border border-emerald-400/20 bg-emerald-500/[.06] px-3 py-2 text-[9px] text-emerald-300 xl:block">● All Systems Operational</span><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/5 bg-white/[.03]"><Bell className="h-4 w-4 text-slate-300"/></div></div></div></header>
 <div className="mx-auto max-w-[1700px] space-y-4 px-3 pb-24 pt-4 sm:px-6 lg:px-8 lg:pb-8"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Metric label="Active Leads" value={String(active)} icon={<Users/>} tone="blue" sub="Live opportunities"/><Metric label="Upcoming Walkthroughs" value={String(props.kpis.upcomingWalkthroughs)} icon={<CalendarDays/>} tone="cyan" sub="Scheduled visits"/><Metric label="Open Follow-Ups" value={String(props.kpis.openFollowups)} icon={<CheckCircle2/>} tone="violet" sub="Need attention"/><Metric label="Completed Jobs" value={String(completed)} icon={<CircleDollarSign/>} tone="green" sub="Closed pipeline"/><div className="col-span-2 xl:col-span-1"><Metric label="Pipeline Value" value={money(pipeline)} icon={<CircleDollarSign/>} tone="amber" sub="Potential revenue"/></div></div>
 <div className="grid min-h-[340px] gap-4 xl:grid-cols-[1.18fr_.88fr_.72fr]"><Panel className="flex min-h-[330px] flex-col p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Business Overview</h2><p className="mt-1 text-[9px] text-slate-600">Estimated pipeline trend</p></div><span className="rounded-lg border border-white/5 bg-white/[.03] px-3 py-1.5 text-[9px] text-slate-400">This Month</span></div><div className="relative mt-5 min-h-[190px] flex-1 overflow-hidden rounded-xl bg-[linear-gradient(rgba(37,99,235,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(37,99,235,.09)_1px,transparent_1px)] bg-[size:100%_25%,16.66%_100%]"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full"><defs><linearGradient id="lineGlow" x1="0" x2="1"><stop offset="0" stopColor="#1687ff"/><stop offset="1" stopColor="#22d3ee"/></linearGradient></defs><polyline points={line} fill="none" stroke="url(#lineGlow)" strokeWidth="2.2" vectorEffect="non-scaling-stroke"/><polyline points={points.map((p,i)=>`${(i/(points.length-1))*100},${94-(p/maxPoint)*48}`).join(" ")} fill="none" stroke="#a855f7" strokeWidth="1.3" opacity=".75" vectorEffect="non-scaling-stroke"/></svg></div><div className="mt-4 grid grid-cols-4 divide-x divide-white/5"><Stat label="Pipeline" value={money(pipeline)}/><Stat label="Leads" value={String(bookings.length)}/><Stat label="Completed" value={String(completed)}/><Stat label="Conversion" value={`${bookings.length?Math.round(completed/bookings.length*100):0}%`}/></div></Panel>
 <Panel className="min-h-[330px] p-5"><h2 className="text-sm font-semibold">Pipeline by Stage</h2><p className="mt-1 text-[9px] text-slate-600">Live opportunity distribution</p><div className="mt-7 flex items-center gap-6"><div className="relative h-40 w-40 shrink-0 rounded-full bg-[conic-gradient(#2587ff_0_34%,#21d7df_34%_60%,#9957ef_60%_82%,#4ade80_82%)] shadow-[0_0_35px_rgba(37,135,255,.18)]"><div className="absolute inset-[29px] flex flex-col items-center justify-center rounded-full border border-blue-400/10 bg-[#041020]"><span className="text-3xl font-semibold">{bookings.length}</span><span className="text-[8px] uppercase tracking-wider text-slate-500">Total Leads</span></div></div><div className="min-w-0 flex-1 space-y-4">{stages.map(s=><div key={s.label} className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:s.color,boxShadow:`0 0 10px ${s.color}`}}/><span className="min-w-0 flex-1 truncate text-[10px] text-slate-300">{s.label}</span><b className="text-xs">{s.value}</b><span className="w-8 text-right text-[8px] text-slate-600">{Math.round(s.value/total*100)}%</span></div>)}</div></div><a href="#leads" className="mt-7 flex h-10 items-center justify-center rounded-xl border border-blue-400/20 bg-blue-500/[.04] text-[10px] text-blue-300">View Full Pipeline <ChevronRight className="ml-1 h-3 w-3"/></a></Panel>
 <Panel className="min-h-[330px] p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Today’s Schedule</h2><p className="mt-1 text-[9px] text-slate-600">Upcoming customer work</p></div><CalendarDays className="h-4 w-4 text-cyan-300"/></div><div className="mt-5 space-y-2">{upcoming.length?upcoming.map((b,i)=><Link key={b.id} href={`/owner/booking/${b.id}`} className="flex items-center gap-3 rounded-xl border border-blue-400/10 bg-[#08182d] p-3 hover:border-cyan-400/25"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${i%2?"bg-violet-500/10 text-violet-300":"bg-cyan-500/10 text-cyan-300"}`}><CalendarDays className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold">{b.bookingType==="followup"?"Follow-Up Walkthrough":"Initial Walkthrough"}</p><p className="mt-1 truncate text-[9px] text-blue-300">{b.customerName}</p><p className="mt-1 text-[8px] text-slate-500">{when(b.scheduledForISO)}</p></div><ChevronRight className="h-3 w-3 text-slate-600"/></Link>):<div className="rounded-xl border border-dashed border-blue-400/10 py-12 text-center text-[10px] text-slate-600">No upcoming walkthroughs.</div>}</div><Link href="/owner/dashboard/calendar" className="mt-4 flex h-10 items-center justify-center rounded-xl border border-blue-400/20 text-[10px] text-blue-300">View Calendar →</Link></Panel></div>
 <div className="grid min-h-[360px] gap-4 xl:grid-cols-[1.35fr_.66fr_.72fr]"><Panel className="overflow-hidden"><div id="leads" className="scroll-mt-24"><div className="flex flex-col gap-3 border-b border-white/5 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">Recent Leads</h2><p className="mt-1 text-[9px] text-slate-600">Website, referral, phone and manual opportunities</p></div><div className="flex gap-2"><button onClick={()=>setShowAdd(true)} className="flex h-9 items-center gap-1.5 rounded-xl border border-cyan-400/20 bg-cyan-500/[.07] px-3 text-[9px] font-semibold text-cyan-200"><Plus className="h-3.5 w-3.5"/>Add Lead</button><div className="flex items-center gap-2 rounded-xl border border-blue-400/10 bg-[#061326] px-3"><Search className="h-3.5 w-3.5 text-blue-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leads" className="h-9 w-28 border-0 bg-transparent p-0 text-[10px] focus-visible:ring-0"/></div></div></div><div className="divide-y divide-white/5">{filtered.length?filtered.map(b=><div key={b.id} className="grid gap-2 p-4 hover:bg-blue-500/[.04] sm:grid-cols-[1.35fr_.65fr_.8fr_.6fr_auto] sm:items-center"><Link href={`/owner/booking/${b.id}`}><p className="text-[11px] font-semibold">{b.customerName}</p><p className="mt-1 text-[8px] text-slate-600">{b.customerEmail||b.customerPhone||"No contact"}</p></Link><span className="text-[9px] text-slate-400">{b.bookingType==="followup"?"Follow-Up":"Initial"}</span><span className="text-[9px] font-medium">{b.roughLow||b.roughHigh?`${money(b.roughLow??0)} – ${money(b.roughHigh??b.roughLow??0)}`:"Pricing pending"}</span><span className="w-fit rounded-md border border-blue-400/20 bg-blue-500/10 px-2 py-1 text-[8px] capitalize text-blue-300">{b.status}</span><button onClick={()=>setDeleteTarget({id:b.id,name:b.customerName})} className="flex h-9 w-9 items-center justify-center rounded-xl border border-rose-400/20 bg-rose-500/[.08] text-rose-400 hover:bg-rose-500/20"><Trash2 className="h-3.5 w-3.5"/></button></div>):<div className="py-16 text-center text-[10px] text-slate-600">No matching leads.</div>}</div></div></Panel>
 <Panel className="p-5"><div className="flex items-center gap-2"><Zap className="h-4 w-4 text-amber-300"/><h2 className="text-sm font-semibold">Reminders & Tasks</h2></div><div className="mt-5 space-y-2"><Task label="Due Today" value={props.reminders.filter(r=>r.bucket==="today").length} tone="rose"/><Task label="Due This Week" value={props.reminders.filter(r=>r.bucket==="week").length} tone="amber"/><Task label="Overdue" value={props.reminders.filter(r=>r.bucket==="overdue").length} tone="rose"/><Task label="Initial Walkthroughs" value={props.reminders.filter(r=>r.kind==="walkthrough").length} tone="blue"/><Task label="Follow-Up Walkthroughs" value={props.reminders.filter(r=>r.kind==="followup").length} tone="green"/></div></Panel>
 <Panel className="p-5"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-300"/><h2 className="text-sm font-semibold">Recent Activity</h2></div><div className="mt-5">{recent.length?recent.map((e,i)=><div key={e.id} className="relative flex min-h-12 gap-3 border-l border-blue-400/20 pb-3 pl-5"><span className={`absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full ${i%3===0?"bg-blue-400":i%3===1?"bg-cyan-300":"bg-violet-400"} shadow-[0_0_10px_currentColor]`}/><div><p className="text-[10px] font-medium">{eventLabel(e.eventType)}</p><p className="mt-1 text-[9px] text-slate-500">{e.customerName}</p><p className="mt-1 text-[8px] text-slate-700">{when(e.occurredAt)}</p></div></div>):<p className="py-12 text-center text-[10px] text-slate-600">No recent activity.</p>}</div></Panel></div>
 <div className="grid gap-4 md:grid-cols-3"><Quick title="New Lead" text="Capture phone, referral or field opportunities." icon={<UserRoundSearch/>} action={()=>setShowAdd(true)} tone="blue"/><Quick title="Walkthroughs" text="Open the field assessment workspace." icon={<ShieldCheck/>} href="/owner/walkthroughs" tone="cyan"/><Quick title="Quotes" text="Move assessed scope into customer pricing." icon={<FileText/>} href="/owner/quotes" tone="violet"/></div></div>
 <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-cyan-400/15 bg-[#020b19]/95 px-1 pb-[max(env(safe-area-inset-bottom),.5rem)] pt-2 backdrop-blur-xl lg:hidden">{navItems.slice(0,5).map(({label,icon:Icon,href})=>href?<Link key={label} href={href} className="flex flex-col items-center gap-1 py-1 text-[8px] text-slate-400"><Icon className="h-4 w-4"/>{label}</Link>:null)}</nav></section>
 {showAdd&&<div className="fixed inset-0 z-[100] flex items-end justify-center p-3 sm:items-center"><button className="absolute inset-0 bg-[#01040b]/85 backdrop-blur-md" onClick={()=>!saving&&setShowAdd(false)}/><form onSubmit={addLead} className="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[26px] border border-cyan-400/25 bg-[linear-gradient(145deg,#071a32,#030b18)] p-5 shadow-[0_0_70px_rgba(0,174,255,.13)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.22em] text-cyan-400">SmartNET CRM</p><h2 className="mt-1 text-xl font-semibold">Add a New Lead</h2><p className="mt-1 text-xs text-slate-500">Capture opportunities that didn’t come through the estimator.</p></div><button type="button" onClick={()=>setShowAdd(false)} className="rounded-xl border border-white/5 p-2 text-slate-500"><X className="h-4 w-4"/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Customer / Company *" value={lead.customerName} set={v=>setLead(x=>({...x,customerName:v}))}/><Field label="Lead Source" value={lead.source} set={v=>setLead(x=>({...x,source:v}))}/><Field label="Email" type="email" value={lead.email} set={v=>setLead(x=>({...x,email:v}))}/><Field label="Phone" type="tel" value={lead.phone} set={v=>setLead(x=>({...x,phone:v}))}/><Field label="Project Type" value={lead.projectType} placeholder="Home, church, warehouse..." set={v=>setLead(x=>({...x,projectType:v}))}/><Field label="Services" value={lead.services} placeholder="Cameras, Wi-Fi, cabling..." set={v=>setLead(x=>({...x,services:v}))}/><div className="sm:col-span-2"><Field label="Job Address / Location" value={lead.address} set={v=>setLead(x=>({...x,address:v}))}/></div><Field label="Rough Low ($)" type="number" value={lead.roughLow} set={v=>setLead(x=>({...x,roughLow:v}))}/><Field label="Rough High ($)" type="number" value={lead.roughHigh} set={v=>setLead(x=>({...x,roughHigh:v}))}/><label className="sm:col-span-2"><span className="mb-2 block text-[9px] uppercase tracking-wider text-slate-500">Notes</span><textarea value={lead.notes} onChange={e=>setLead(x=>({...x,notes:e.target.value}))} rows={4} className="w-full rounded-xl border border-blue-400/15 bg-[#031020] px-3 py-3 text-xs outline-none focus:border-cyan-400/40" placeholder="What does the customer need?"/></label></div><p className="mt-4 text-[9px] text-slate-600">Customer name plus either email or phone is required.</p><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" disabled={saving} onClick={()=>setShowAdd(false)} className="h-11 rounded-xl border border-white/10 bg-white/[.03] text-xs text-slate-300">Cancel</button><button disabled={saving} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-cyan-300/30 bg-blue-600/25 text-xs font-semibold text-cyan-100 shadow-[0_0_24px_rgba(37,99,235,.15)]"><Plus className="h-4 w-4"/>{saving?"Adding...":"Add to Pipeline"}</button></div></form></div>}
 {deleteTarget&&<div className="fixed inset-0 z-[100] flex items-end justify-center p-3 sm:items-center"><button className="absolute inset-0 bg-[#01040b]/85 backdrop-blur-md" onClick={()=>!deleting&&setDeleteTarget(null)}/><div className="relative w-full max-w-md rounded-[24px] border border-rose-400/25 bg-[linear-gradient(145deg,#08172d,#040c19)] p-6"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-rose-400/20 bg-rose-500/10"><TriangleAlert className="h-5 w-5 text-rose-300"/></div><div><p className="text-[9px] uppercase tracking-[.22em] text-rose-400">Remove Lead</p><h2 className="mt-1 text-lg font-semibold">Delete {deleteTarget.name}?</h2><p className="mt-2 text-xs leading-5 text-slate-400">This permanently removes this lead/walkthrough record.</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><button disabled={deleting} onClick={()=>setDeleteTarget(null)} className="h-11 rounded-xl border border-white/10 bg-white/[.03] text-xs">Cancel</button><button disabled={deleting} onClick={()=>void removeLead()} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-rose-400/30 bg-rose-500/15 text-xs text-rose-200"><Trash2 className="h-4 w-4"/>{deleting?"Removing...":"Remove Lead"}</button></div></div></div>}{notice&&<div className="fixed bottom-24 left-1/2 z-[110] -translate-x-1/2 rounded-xl border border-cyan-400/20 bg-[#07172b] px-4 py-3 text-xs text-cyan-100 shadow-2xl">{notice}</div>}</main>;
};
function OwnerNav({onNavigate}:{onNavigate?:()=>void}){return <nav className="space-y-1">{navItems.map(({label,icon:Icon,href})=>href?<Link key={label} href={href} onClick={onNavigate} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-xs ${label==="Dashboard"?"border border-blue-400/25 bg-blue-600/25 text-white":"text-slate-300 hover:bg-blue-500/10"}`}><Icon className="h-4 w-4"/>{label}</Link>:<div key={label} className="flex items-center gap-3 px-3 py-2.5 text-xs text-slate-600"><Icon className="h-4 w-4"/>{label}</div>)}</nav>}
function Brand(){return <div><p className="text-2xl font-semibold">Smart<span className="text-blue-400">NET</span></p><p className="text-[8px] uppercase tracking-[.3em] text-slate-400">Owner Console</p></div>}
function Panel({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-blue-400/15 bg-[linear-gradient(145deg,rgba(4,16,34,.98),rgba(3,12,27,.97))] shadow-[0_18px_60px_rgba(0,0,0,.3)] ${className}`}>{children}</section>}
const tones={blue:"border-blue-400/50 bg-blue-500/10 text-blue-300 shadow-[0_0_28px_rgba(37,99,235,.32)]",cyan:"border-cyan-300/50 bg-cyan-400/10 text-cyan-200 shadow-[0_0_28px_rgba(34,211,238,.30)]",violet:"border-violet-400/50 bg-violet-500/10 text-violet-300 shadow-[0_0_28px_rgba(139,92,246,.30)]",green:"border-emerald-400/50 bg-emerald-500/10 text-emerald-300 shadow-[0_0_28px_rgba(74,222,128,.28)]",amber:"border-amber-300/50 bg-amber-400/10 text-amber-200 shadow-[0_0_28px_rgba(251,191,36,.28)]"};
function Metric({label,value,icon,tone,sub}:{label:string;value:string;icon:ReactNode;tone:keyof typeof tones;sub:string}){return <Panel className="min-h-[112px] p-4"><div className="flex items-center gap-3"><div className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-full border ${tones[tone]} [&>svg]:h-6 [&>svg]:w-6`}>{icon}</div><div className="min-w-0"><p className="truncate text-[8px] uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 truncate text-2xl font-semibold">{value}</p><p className="mt-1 text-[8px] text-emerald-400">▲ {sub}</p></div></div></Panel>}
function Stat({label,value}:{label:string;value:string}){return <div className="px-3"><p className="text-[7px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Task({label,value,tone}:{label:string;value:number;tone:"rose"|"amber"|"blue"|"green"}){const c={rose:"bg-rose-500/15 text-rose-300",amber:"bg-amber-500/15 text-amber-300",blue:"bg-blue-500/15 text-blue-300",green:"bg-emerald-500/15 text-emerald-300"}[tone];return <div className="flex items-center gap-3 rounded-xl border border-white/[.025] bg-[#08182d] p-3"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${c}`}><Zap className="h-3.5 w-3.5"/></div><span className="flex-1 text-[10px]">{label}</span><b className="text-xs">{value}</b></div>}
function Quick({title,text,icon,href,action,tone}:{title:string;text:string;icon:ReactNode;href?:string;action?:()=>void;tone:"blue"|"cyan"|"violet"}){const c={blue:"text-blue-300 bg-blue-500/10 border-blue-400/20",cyan:"text-cyan-300 bg-cyan-500/10 border-cyan-400/20",violet:"text-violet-300 bg-violet-500/10 border-violet-400/20"}[tone];const body=<Panel className="flex min-h-[118px] items-center gap-4 p-5 transition hover:-translate-y-0.5"><div className={`flex h-12 w-12 items-center justify-center rounded-xl border ${c} [&>svg]:h-5 [&>svg]:w-5`}>{icon}</div><div className="flex-1"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-[9px] text-slate-500">{text}</p></div><ChevronRight className="h-4 w-4 text-slate-600"/></Panel>;return href?<Link href={href}>{body}</Link>:<button onClick={action} className="text-left">{body}</button>}
function Field({label,value,set,type="text",placeholder=""}:{label:string;value:string;set:(v:string)=>void;type?:string;placeholder?:string}){return <label><span className="mb-2 block text-[9px] uppercase tracking-wider text-slate-500">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-blue-400/15 bg-[#031020] px-3 text-xs outline-none focus:border-cyan-400/40"/></label>}
