import type { ReactElement } from "react";
import { sanityWriteClient } from "@/lib/sanityWriteClient";
import { OwnerCustomersClient, type OwnerCustomer } from "@/components/owner/OwnerCustomersClient";

type Doc={_id:string;status?:string;appointmentType?:string;contactName?:string;contactEmail?:string;contactPhone?:string;estimateRoughRange?:string|null;estimateTotal?:number|null;createdAt?:string|null;dateISO?:string|null;jobLocationNote?:string|null;leadSource?:string|null;projectType?:string|null;requestedServices?:string|null};
const num=(s:string)=>{const n=Number(s.replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null};
function range(v?:string|null):[number|null,number|null]{if(!v)return[null,null];const p=v.split("–").map(x=>x.trim());return p.length===2?[num(p[0]),num(p[1])]:[null,null]}
function key(d:Doc){const email=d.contactEmail?.trim().toLowerCase();if(email)return`e:${email}`;const phone=d.contactPhone?.replace(/\D/g,"");if(phone)return`p:${phone}`;return`n:${(d.contactName||"unknown").trim().toLowerCase()}`}
function status(docs:Doc[]):OwnerCustomer["status"]{if(docs.some(d=>(d.status||"").toLowerCase().includes("complete")))return"customer";if(docs.some(d=>(d.status||"").toLowerCase().includes("follow")))return"followup";if(docs.some(d=>(d.status||"").toLowerCase().includes("sched")))return"scheduled";return"lead"}
async function getCustomers():Promise<OwnerCustomer[]>{const docs=await sanityWriteClient.fetch<Doc[]>(`*[_type == "walkthroughBooking"] | order(createdAt desc){_id,status,appointmentType,contactName,contactEmail,contactPhone,estimateRoughRange,estimateTotal,createdAt,dateISO,jobLocationNote,leadSource,projectType,requestedServices}`);const groups=new Map<string,Doc[]>();for(const d of docs){const k=key(d);groups.set(k,[...(groups.get(k)||[]),d])}return [...groups.values()].map(g=>{const latest=g.slice().sort((a,b)=>new Date(b.createdAt||b.dateISO||0).getTime()-new Date(a.createdAt||a.dateISO||0).getTime())[0];let value=0;for(const d of g){const[,hi]=range(d.estimateRoughRange);value+=hi??d.estimateTotal??0}return{id:key(latest),name:latest.contactName||"Unknown customer",email:latest.contactEmail||null,phone:latest.contactPhone||null,location:latest.jobLocationNote||null,source:latest.leadSource||null,projectType:latest.projectType||null,services:latest.requestedServices||null,status:status(g),opportunities:g.length,lifetimeValue:value,lastActivity:latest.createdAt||latest.dateISO||null,bookingIds:g.map(d=>d._id)}}).sort((a,b)=>new Date(b.lastActivity||0).getTime()-new Date(a.lastActivity||0).getTime())}
export default async function OwnerCustomersPage():Promise<ReactElement>{return <OwnerCustomersClient customers={await getCustomers()}/>}
