import type { ReactElement } from "react";
import { sanityWriteClient } from "@/lib/sanityWriteClient";
import { OwnerFollowUpsClient, type OwnerFollowUp } from "@/components/owner/OwnerFollowUpsClient";

type Doc={_id:string;status?:string;contactName?:string;contactEmail?:string;contactPhone?:string;dateISO?:string|null;timeSlot?:string|null;followupWalkthroughDateISO?:string|null;followupWalkthroughTimeSlot?:string|null;estimateRoughRange?:string|null;estimateTotal?:number|null;jobLocationNote?:string|null;projectType?:string|null;requestedServices?:string|null;createdAt?:string|null};
const numberFrom=(s:string)=>{const n=Number(s.replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null};
function value(d:Doc){if(d.estimateRoughRange){const p=d.estimateRoughRange.split("–").map(numberFrom);if(p.length===2)return p[1]??p[0]??0}return d.estimateTotal??0}
function state(d:Doc):OwnerFollowUp["state"]{const s=(d.status||"").toLowerCase();if(s.includes("complete")||s.includes("done"))return"completed";if(d.followupWalkthroughDateISO){const dt=new Date(d.followupWalkthroughDateISO);if(dt.getTime()<Date.now())return"overdue";return"scheduled"}if(s.includes("follow"))return"needs_action";return"needs_action"}
async function getFollowUps():Promise<OwnerFollowUp[]>{const docs=await sanityWriteClient.fetch<Doc[]>(`*[_type == "walkthroughBooking" && (status match "*follow*" || defined(followupWalkthroughDateISO))] | order(followupWalkthroughDateISO asc){_id,status,contactName,contactEmail,contactPhone,dateISO,timeSlot,followupWalkthroughDateISO,followupWalkthroughTimeSlot,estimateRoughRange,estimateTotal,jobLocationNote,projectType,requestedServices,createdAt}`);return docs.map(d=>({id:d._id,customerName:d.contactName||"Unknown customer",email:d.contactEmail||null,phone:d.contactPhone||null,location:d.jobLocationNote||null,projectType:d.projectType||null,services:d.requestedServices||null,state:state(d),scheduledFor:d.followupWalkthroughDateISO||null,timeSlot:d.followupWalkthroughTimeSlot||null,originalWalkthrough:d.dateISO||null,pipelineValue:value(d),createdAt:d.createdAt||null}))}
export default async function OwnerFollowUpsPage():Promise<ReactElement>{return <OwnerFollowUpsClient followUps={await getFollowUps()}/>}
