import type { ReactElement } from "react";
import { OwnerDashboardClient } from "@/components/owner/OwnerDashboardClient";
import { estimateHigh, followUpDueAt, getOwnerLifecycleData, isActiveJob, isCompleted } from "@/lib/owner/ownerData";

export type BookingStatus="new"|"scheduled"|"followup"|"completed"|"unknown";
export type OwnerBooking={id:string;customerName:string;customerEmail?:string|null;customerPhone?:string|null;bookingType:"initial"|"followup";scheduledForISO:string|null;status:BookingStatus;roughLow?:number|null;roughHigh?:number|null};
export type ReminderItem={id:string;label:string;when:string;bucket:"today"|"week"|"overdue";bookingId:string;kind:"walkthrough"|"followup"};
export type LeadEvent={id:string;customerName:string;eventType:string;occurredAt:string;bookingId?:string;leadId?:string;jobId?:string;quoteId?:string};
export type OwnerDashboardData={bookings:OwnerBooking[];reminders:ReminderItem[];leadEvents:LeadEvent[];kpis:{activeLeads:number;upcomingWalkthroughs:number;openFollowups:number;activeJobs:number;completedJobs:number;quotePipeline:number;approvedQuoteValue:number}};

function normalizeStatus(status:string|undefined|null,bookingType:OwnerBooking["bookingType"]):BookingStatus{if(!status)return bookingType==="followup"?"followup":"scheduled";const s=status.toLowerCase();if(s.includes("new"))return"new";if(s.includes("sched"))return"scheduled";if(s.includes("follow"))return"followup";if(s.includes("complete")||s.includes("done"))return"completed";return"unknown"}
function parseEstimateRange(range?:string|null):[number|null,number|null]{if(!range)return[null,null];const parts=range.split("–").map(p=>p.trim());if(parts.length!==2)return[null,null];const p=(s:string)=>{const n=Number(s.replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null};return[p(parts[0]),p(parts[1])]}
function startOfDay(d:Date){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function bucket(date:Date):"today"|"week"|"overdue"|null{const today=startOfDay(new Date()),week=new Date(today.getTime()+7*86400000),x=startOfDay(date).getTime();if(x===today.getTime())return"today";if(x>today.getTime()&&x<=week.getTime())return"week";if(x<today.getTime())return"overdue";return null}
function friendly(date:Date,time?:string|null){const d=date.toLocaleDateString("en-US",{month:"short",day:"numeric"});return time?`${d} • ${time}`:d}

async function getData():Promise<OwnerDashboardData>{const{bookings:docs,jobs,quotes,activities,settings}=await getOwnerLifecycleData();const bookings:OwnerBooking[]=docs.map(doc=>{const typeRaw=(doc.appointmentType||"").toLowerCase(),bookingType:OwnerBooking["bookingType"]=typeRaw.includes("follow")?"followup":"initial";const[roughLow,roughHigh]=parseEstimateRange(doc.estimateRoughRange);return{id:doc._id,customerName:doc.contactName||"Unknown customer",customerEmail:doc.contactEmail||undefined,customerPhone:doc.contactPhone||undefined,bookingType,scheduledForISO:doc.dateISO||null,status:normalizeStatus(doc.status,bookingType),roughLow:roughLow??doc.estimateTotal??undefined,roughHigh:roughHigh??undefined}});const reminders:ReminderItem[]=[];for(const doc of docs){if(isCompleted(doc.status))continue;if(doc.dateISO){const d=new Date(doc.dateISO),b=bucket(d);if(b)reminders.push({id:`${doc._id}-walkthrough`,label:`Walkthrough – ${doc.contactName||"Unknown customer"}`,when:friendly(d,doc.timeSlot),bucket:b,bookingId:doc._id,kind:"walkthrough"})}const due=followUpDueAt(doc,settings);if(due){const d=new Date(due),b=bucket(d);if(b)reminders.push({id:`${doc._id}-followup`,label:`Follow-up – ${doc.contactName||"Unknown customer"}`,when:friendly(d,doc.followupWalkthroughTimeSlot),bucket:b,bookingId:doc._id,kind:"followup"})}}
const inferred:LeadEvent[]=docs.map(d=>({id:`${d._id}-booking`,customerName:d.contactName||"Unknown customer",eventType:"booking_created",occurredAt:d.createdAt||d.dateISO||new Date(0).toISOString(),bookingId:d._id}));const leadEvents:LeadEvent[]=[...activities.map(a=>({id:a._id,customerName:a.customerName||"SmartNET customer",eventType:a.eventType,occurredAt:a.occurredAt,bookingId:a.bookingId||undefined,jobId:a.jobId||undefined,quoteId:a.quoteId||undefined})),...inferred].sort((a,b)=>new Date(b.occurredAt).getTime()-new Date(a.occurredAt).getTime()).slice(0,100);const activeLeads=new Set(bookings.filter(b=>b.status!=="completed").map(b=>b.customerEmail||b.customerPhone||b.id)).size;const upcomingWalkthroughs=bookings.filter(b=>(b.status==="scheduled"||b.status==="new")&&b.scheduledForISO&&new Date(b.scheduledForISO)>=new Date()).length;const openFollowups=reminders.filter(r=>r.kind==="followup").length;const activeJobs=jobs.filter(j=>isActiveJob(j.status)).length,completedJobs=jobs.filter(j=>isCompleted(j.status)).length;const quotePipeline=quotes.filter(q=>q.status!=="declined").reduce((s,q)=>s+(q.amount||0),0),approvedQuoteValue=quotes.filter(q=>q.status==="approved").reduce((s,q)=>s+(q.amount||0),0);return{bookings,reminders,leadEvents,kpis:{activeLeads,upcomingWalkthroughs,openFollowups,activeJobs,completedJobs,quotePipeline,approvedQuoteValue}}}
export default async function OwnerDashboardPage():Promise<ReactElement>{return <OwnerDashboardClient {...await getData()}/>}
