import Link from "next/link";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, MapPin, Network, ShieldCheck, Wrench } from "lucide-react";
import { sanityWriteClient } from "@/lib/sanityWriteClient";
import { ConvertToJobButton } from "@/components/owner/ConvertToJobButton";

type Walkthrough = {
  _id:string; status?:string|null; contactName?:string|null; contactEmail?:string|null; contactPhone?:string|null;
  locationLabel?:string|null; locationType?:string|null; estimateRoughRange?:string|null; estimateTotal?:number|null;
  rawEstimateJson?:string|null;
};
type Job = {
  _id:string; sourceBookingId:string; status?:string|null; customerName?:string|null; locationLabel?:string|null; locationType?:string|null;
  estimateRoughRange?:string|null; estimateTotal?:number|null; createdAt?:string|null; installDateISO?:string|null;
};
type Estimate = { projectType?:string; focus?:string[]; [key:string]:unknown };

async function getData(){
  const [walkthroughs,jobs]=await Promise.all([
    sanityWriteClient.fetch<Walkthrough[]>(`*[_type == "walkthroughBooking"] | order(dateISO desc){_id,status,contactName,contactEmail,contactPhone,locationLabel,locationType,estimateRoughRange,estimateTotal,rawEstimateJson}`),
    sanityWriteClient.fetch<Job[]>(`*[_type == "smartnetJob"] | order(createdAt desc){_id,sourceBookingId,status,customerName,locationLabel,locationType,estimateRoughRange,estimateTotal,createdAt,installDateISO}`),
  ]);
  return {walkthroughs,jobs};
}
function isCompleted(s?:string|null){const v=(s||"").toLowerCase();return v.includes("complete")||v.includes("done")}
function estimate(w:Walkthrough):Estimate|null{if(!w.rawEstimateJson)return null;try{return JSON.parse(w.rawEstimateJson) as Estimate}catch{return null}}
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v)}
function jobStatus(s?:string|null){const v=(s||"draft").toLowerCase();if(v.includes("progress"))return"In Progress";if(v.includes("scheduled"))return"Scheduled";if(v.includes("complete"))return"Completed";return"Draft"}

export default async function JobsPage(){
 const {walkthroughs,jobs}=await getData();
 const converted=new Set(jobs.map(j=>j.sourceBookingId));
 const ready=walkthroughs.filter(w=>isCompleted(w.status)&&!converted.has(w._id));
 const scheduled=jobs.filter(j=>jobStatus(j.status)==="Scheduled");
 const inProgress=jobs.filter(j=>jobStatus(j.status)==="In Progress");
 const activeValue=jobs.filter(j=>jobStatus(j.status)!=="Completed").reduce((s,j)=>s+(j.estimateTotal||0),0);
 return <main className="min-h-screen bg-[#020713] text-slate-100"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_0%,rgba(0,132,255,.14),transparent_30%),radial-gradient(circle_at_85%_10%,rgba(34,211,238,.09),transparent_28%),linear-gradient(rgba(15,34,58,.17)_1px,transparent_1px),linear-gradient(90deg,rgba(15,34,58,.17)_1px,transparent_1px)] bg-[size:auto,auto,40px_40px,40px_40px]"/>
 <header className="sticky top-0 z-30 border-b border-cyan-400/10 bg-[#020713]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-blue-400/30 bg-blue-500/10"><Network className="h-4 w-4 text-cyan-300"/></div><div><p className="text-sm font-semibold">Smart<span className="text-blue-400">NET</span></p><p className="text-[9px] uppercase tracking-[.24em] text-slate-600">Job Operations</p></div></div><Link href="/owner/dashboard" className="flex items-center gap-2 rounded-xl border border-white/5 bg-white/[.03] px-3 py-2 text-xs text-slate-300"><ArrowLeft className="h-3.5 w-3.5"/>Command Center</Link></div></header>
 <div className="relative mx-auto max-w-[1500px] space-y-5 px-3 pb-20 pt-5 sm:px-6 lg:px-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-cyan-500">Installation Operations</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Jobs Command</h1><p className="mt-1 text-xs text-slate-500">Convert assessed projects into real SmartNET job records.</p></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Active Jobs" value={String(jobs.filter(j=>jobStatus(j.status)!=="Completed").length)} icon={<BriefcaseBusiness className="h-5 w-5 text-blue-300"/>}/><Metric label="Scheduled" value={String(scheduled.length)} icon={<CalendarDays className="h-5 w-5 text-cyan-300"/>}/><Metric label="In Progress" value={String(inProgress.length)} icon={<Wrench className="h-5 w-5 text-violet-300"/>}/><Metric label="Active Value" value={money(activeValue)} icon={<CircleDollarSign className="h-5 w-5 text-amber-300"/>}/></div>

 {jobs.length>0&&<section className="overflow-hidden rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))]"><div className="border-b border-white/5 p-5"><div className="flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-cyan-300"/><h2 className="text-sm font-semibold">Active Job Records</h2></div><p className="mt-1 text-[10px] text-slate-600">Real jobs created from completed walkthroughs</p></div><div className="divide-y divide-white/5">{jobs.map(j=><div key={j._id} className="p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold">{j.customerName||"Unknown customer"}</p><span className="rounded-full border border-cyan-400/15 bg-cyan-500/[.07] px-2 py-1 text-[8px] uppercase tracking-wider text-cyan-300">{jobStatus(j.status)}</span></div><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-slate-500"><span className="flex items-center gap-1"><MapPin className="h-3 w-3"/>{j.locationLabel||j.locationType||"Location not specified"}</span><span className="text-amber-300/80">{j.estimateRoughRange||money(j.estimateTotal||0)}</span></div></div><Link href={`/owner/booking/${j.sourceBookingId}`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-4 text-[10px] text-slate-200">Customer Record<ArrowRight className="h-3.5 w-3.5"/></Link></div></div>)}</div></section>}

 <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="overflow-hidden rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))]"><div className="border-b border-white/5 p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300"/><h2 className="text-sm font-semibold">Ready to Convert</h2></div><p className="mt-1 text-[10px] text-slate-600">Completed walkthroughs that do not have a Job record yet</p></div><div className="divide-y divide-white/5">{ready.length?ready.map(w=><ReadyRow key={w._id} w={w}/>):<div className="p-10 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-emerald-900"/><p className="mt-3 text-xs text-slate-500">No projects waiting for conversion.</p></div>}</div></section>
 <aside className="space-y-5"><div className="rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))] p-5"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-cyan-300"/><h2 className="text-sm font-semibold">Job Flow</h2></div><div className="mt-5 space-y-4"><Flow n="01" label="Walkthrough Complete" active/><Flow n="02" label="Convert to Job" active/><Flow n="03" label="Final Scope / Quote"/><Flow n="04" label="Schedule Installation"/><Flow n="05" label="Install & Close"/></div></div><div className="rounded-2xl border border-emerald-400/10 bg-emerald-500/[.035] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-emerald-300">Real Lifecycle Enabled</p><p className="mt-2 text-[11px] leading-5 text-slate-500">Convert to Job now creates a dedicated <span className="text-slate-300">smartnetJob</span> document in Sanity and links it back to the original customer walkthrough.</p></div></aside></div>
 </div></main>
}
function ReadyRow({w}:{w:Walkthrough}){const e=estimate(w);const focus=Array.isArray(e?.focus)&&e!.focus!.length?e!.focus!.join(" · "):"Scope available in customer record";return <div className="p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><Link href={`/owner/booking/${w._id}`} className="min-w-0 flex-1"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400"/><p className="text-sm font-semibold">{w.contactName||"Unknown customer"}</p><span className="rounded-full border border-emerald-400/15 bg-emerald-500/[.07] px-2 py-1 text-[8px] uppercase tracking-wider text-emerald-300">Assessed</span></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-slate-500"><span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-blue-400"/>{w.locationLabel||w.locationType||"Location not specified"}</span><span>{e?.projectType||"Project"}</span><span className="text-amber-300/80">{w.estimateRoughRange||money(w.estimateTotal||0)}</span></div><p className="mt-2 truncate text-[10px] text-slate-600">{focus}</p></Link><div className="flex flex-col gap-2 sm:flex-row"><Link href={`/owner/booking/${w._id}`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-4 text-[10px] text-slate-300">Review<ArrowRight className="h-3.5 w-3.5"/></Link><ConvertToJobButton bookingId={w._id}/></div></div></div>}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="rounded-2xl border border-cyan-400/10 bg-[linear-gradient(145deg,rgba(8,18,36,.95),rgba(3,10,24,.97))] p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/5 bg-white/[.03]">{icon}</div><div><p className="text-[9px] uppercase tracking-[.16em] text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div></div></div>}
function Flow({n,label,active=false}:{n:string;label:string;active?:boolean}){return <div className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-lg border text-[9px] font-semibold ${active?"border-cyan-400/25 bg-cyan-500/10 text-cyan-300":"border-white/5 bg-white/[.02] text-slate-700"}`}>{n}</div><span className={`text-[11px] ${active?"text-slate-300":"text-slate-600"}`}>{label}</span></div>}
