import { sanityWriteClient } from "@/lib/sanityWriteClient";

export type OwnerSettings={businessName:string;businessEmail:string;businessPhone:string;businessAddress:string;timezone:string;defaultLeadSource:string;defaultFollowUpDays:number;quoteExpirationDays:number;walkthroughDurationMinutes:number;businessHoursStart:string;businessHoursEnd:string;notifications:{newLead:boolean;walkthrough:boolean;followUp:boolean;quoteApproved:boolean};automation:{autoFollowUp:boolean;showPipelineValues:boolean;customerDeduplication:boolean}};
export const ownerSettingsDefaults:OwnerSettings={businessName:"SmartNET Installation LLC",businessEmail:"",businessPhone:"",businessAddress:"",timezone:"America/New_York",defaultLeadSource:"Website / Estimator",defaultFollowUpDays:2,quoteExpirationDays:14,walkthroughDurationMinutes:60,businessHoursStart:"08:00",businessHoursEnd:"18:00",notifications:{newLead:true,walkthrough:true,followUp:true,quoteApproved:true},automation:{autoFollowUp:true,showPipelineValues:true,customerDeduplication:true}};
export type OwnerBookingDoc={_id:string;status?:string|null;appointmentType?:string|null;dateISO?:string|null;timeSlot?:string|null;contactName?:string|null;contactEmail?:string|null;contactPhone?:string|null;estimateRoughRange?:string|null;estimateTotal?:number|null;createdAt?:string|null;followupWalkthroughDateISO?:string|null;followupWalkthroughTimeSlot?:string|null;ownerFollowUpDueAt?:string|null;leadSource?:string|null;crmStage?:string|null;crmPriority?:string|null;crmAssignedTo?:string|null;crmLostReason?:string|null;crmUpdatedAt?:string|null};
export type OwnerJobDoc={_id:string;sourceBookingId?:string|null;status?:string|null;customerName?:string|null;estimateTotal?:number|null;estimateRoughRange?:string|null;createdAt?:string|null;updatedAt?:string|null;installDateISO?:string|null};
export type OwnerQuoteDoc={_id:string;sourceBookingId?:string|null;sourceJobId?:string|null;status?:string|null;customerName?:string|null;amount?:number|null;createdAt?:string|null;sentAt?:string|null;approvedAt?:string|null;expiresAt?:string|null};
export type OwnerActivityDoc={_id:string;eventType:string;customerName?:string|null;bookingId?:string|null;jobId?:string|null;quoteId?:string|null;occurredAt:string};
export async function getOwnerSettings():Promise<OwnerSettings>{const doc=await sanityWriteClient.fetch<any>(`*[_id=="smartnet-owner-settings"][0]{...}`);if(!doc)return ownerSettingsDefaults;return{...ownerSettingsDefaults,...doc,notifications:{...ownerSettingsDefaults.notifications,...doc.notifications},automation:{...ownerSettingsDefaults.automation,...doc.automation}}}
export async function getOwnerLifecycleData(){const[bookings,jobs,quotes,activities,settings]=await Promise.all([sanityWriteClient.fetch<OwnerBookingDoc[]>(`*[_type=="walkthroughBooking"]|order(coalesce(crmUpdatedAt,createdAt,dateISO) desc)[0...500]{_id,status,appointmentType,dateISO,timeSlot,contactName,contactEmail,contactPhone,estimateRoughRange,estimateTotal,createdAt,followupWalkthroughDateISO,followupWalkthroughTimeSlot,ownerFollowUpDueAt,leadSource,crmStage,crmPriority,crmAssignedTo,crmLostReason,crmUpdatedAt}`),sanityWriteClient.fetch<OwnerJobDoc[]>(`*[_type=="smartnetJob"]|order(createdAt desc)[0...250]{_id,sourceBookingId,status,customerName,estimateTotal,estimateRoughRange,createdAt,updatedAt,installDateISO}`),sanityWriteClient.fetch<OwnerQuoteDoc[]>(`*[_type=="smartnetQuote"]|order(createdAt desc)[0...250]{_id,sourceBookingId,sourceJobId,status,customerName,amount,createdAt,sentAt,approvedAt,expiresAt}`),sanityWriteClient.fetch<OwnerActivityDoc[]>(`*[_type=="smartnetActivity"]|order(occurredAt desc)[0...200]{_id,eventType,customerName,bookingId,jobId,quoteId,occurredAt}`),getOwnerSettings()]);return{bookings,jobs,quotes,activities,settings}}
export function estimateHigh(b:OwnerBookingDoc){if(typeof b.estimateTotal==="number")return b.estimateTotal;if(!b.estimateRoughRange)return 0;const parts=b.estimateRoughRange.split("–");const raw=(parts[1]||parts[0]||"").replace(/[^0-9.]/g,"");const n=Number(raw);return Number.isFinite(n)?n:0}
export function isCompleted(status?:string|null){const s=(status||"").toLowerCase();return s.includes("complete")||s.includes("done")}
export function isClosedLead(b:OwnerBookingDoc){return b.crmStage==="won"||b.crmStage==="lost"||isCompleted(b.status)}
export function isActiveJob(status?:string|null){return !isCompleted(status)}
export function followUpDueAt(b:OwnerBookingDoc,settings:OwnerSettings){if(b.crmStage==="won"||b.crmStage==="lost")return null;if(b.followupWalkthroughDateISO)return b.followupWalkthroughDateISO;if(b.ownerFollowUpDueAt)return b.ownerFollowUpDueAt;if(!settings.automation.autoFollowUp||isCompleted(b.status))return null;const base=b.crmUpdatedAt||b.createdAt||b.dateISO;if(!base)return null;const d=new Date(base);d.setDate(d.getDate()+settings.defaultFollowUpDays);return d.toISOString()}
export async function recordOwnerActivity(input:{eventType:string;customerName?:string|null;bookingId?:string|null;jobId?:string|null;quoteId?:string|null}){const occurredAt=new Date().toISOString();return sanityWriteClient.create({_type:"smartnetActivity",...input,occurredAt})}
