"use client";

import type { FormEvent } from "react";
import { TriangleAlert, X } from "lucide-react";

export type LeadForm={customerName:string;email:string;phone:string;projectType:string;services:string;source:string;address:string;notes:string;roughLow:string;roughHigh:string};
export const emptyLead:LeadForm={customerName:"",email:"",phone:"",projectType:"",services:"",source:"Phone / Referral",address:"",notes:"",roughLow:"",roughHigh:""};

export function AddLeadModal({open,saving,lead,setLead,onClose,onSubmit}:{open:boolean;saving:boolean;lead:LeadForm;setLead:(v:LeadForm)=>void;onClose:()=>void;onSubmit:(e:FormEvent)=>void}){if(!open)return null;const set=(key:keyof LeadForm)=>(v:string)=>setLead({...lead,[key]:v});return <div className="fixed inset-0 z-[100] flex items-end justify-center p-3 sm:items-center"><button className="absolute inset-0 bg-black/85" onClick={onClose}/><form onSubmit={onSubmit} className="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[26px] border border-cyan-400/25 bg-[#061326] p-6"><div className="flex justify-between"><div><p className="text-[9px] text-cyan-400">SMARTNET CRM</p><h2 className="text-xl font-semibold">Add a New Lead</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Customer / Company *" value={lead.customerName} set={set("customerName")}/><Field label="Lead Source" value={lead.source} set={set("source")}/><Field label="Email" value={lead.email} set={set("email")}/><Field label="Phone" value={lead.phone} set={set("phone")}/><Field label="Project Type" value={lead.projectType} set={set("projectType")}/><Field label="Services" value={lead.services} set={set("services")}/><Field label="Address" value={lead.address} set={set("address")}/><Field label="Rough Low" value={lead.roughLow} set={set("roughLow")}/><Field label="Rough High" value={lead.roughHigh} set={set("roughHigh")}/></div><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} className="h-11 rounded-xl border border-white/10">Cancel</button><button disabled={saving} className="h-11 rounded-xl bg-blue-600/30">{saving?"Adding...":"Add to Pipeline"}</button></div></form></div>}
export function DeleteLeadModal({name,deleting,onClose,onDelete}:{name:string|null;deleting:boolean;onClose:()=>void;onDelete:()=>void}){if(!name)return null;return <div className="fixed inset-0 z-[100] flex items-center justify-center p-3"><button className="absolute inset-0 bg-black/85" onClick={onClose}/><div className="relative max-w-md rounded-2xl border border-rose-400/25 bg-[#08172d] p-6"><TriangleAlert className="text-rose-300"/><h2 className="mt-3 text-lg">Delete {name}?</h2><div className="mt-5 flex gap-3"><button onClick={onClose} className="h-10 flex-1 rounded-xl border border-white/10">Cancel</button><button onClick={onDelete} className="h-10 flex-1 rounded-xl bg-rose-500/15 text-rose-200">{deleting?"Removing...":"Remove"}</button></div></div></div>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label><span className="mb-2 block text-[9px] text-slate-500">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-xl border border-blue-400/15 bg-[#031020] px-3 text-xs outline-none"/></label>}
